name: Dev Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, dev-deployment]
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "PORT=2020" >> .env
          echo "ACCESS_TOKEN_SECRET='Ux7#pL3@qR8*vZ2!fY6^wN4&jH1'" >> .env
          echo "REFRESH_TOKEN_SECRET=\"Bx9\$tR2#eF7@mL5*cQ1!hG4^yP8&kS3\"" >> .env
          echo "DB_USER={{ secrets.DB_USER }}" >> .env
          echo "DB_HOST={{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME={{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD={{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=5432" >> .env


      - name: Install dependencies
        run: npm i

      - name: Start application
        run: |
          pm2 delete vibesale-backend || true
          pm2 start "npm run dev" --name vibesale-backend 